### PR TITLE
go-proto: add go.mod and bump protoc-gen-go to v1.27.1

### PR DESCRIPTION
**Pull request by zhsj**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by zhsj** [comment]
And a new tag? BTW if you don't want to bump version for the entire repo, maybe a tag like `go-proto/v1.0.1` (I guess it will work for go mod)

**Comment by AkihiroSuda** [comment]
done
https://github.com/rootless-containers/proto/releases/tag/v0.1.1

**Comment by zhsj** [comment]
Thanks

**Comment by zhsj** [comment]
Seems a bit confused to pkg.go.dev...

https://pkg.go.dev/github.com/rootless-containers/proto@v0.1.1
https://pkg.go.dev/github.com/rootless-containers/proto/go-proto@v0.1.1

Neither works..

**Comment by zhsj** [comment]
Will wait sometime to check again, maybe pkg.go.dev has lag.

**Pull request merged**
